# EverReport - By Rodrigo R. - v.1.1

discord: # Log also reports to discord?
  allow: false
  bot_token: "..." # Get it from: https://discord.com/developers
  guild_id: "..." # Your server ID. More info: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
  channel_id: "..." # The logs channel id
  embed: # The embed to send
    title: "New Report"
    color: "red" # All colors available on java.awt.Color. See: https://docs.oracle.com/javase/8/docs/api/java/awt/Color.html
    author:
      name: "EverReport"
      url: null # Leave it as null to not display
      icon_url: null # Leave it as null to not display
    description:
      - "A new report has been received."
      - "Executor: {executor}"
      - "Reported: {reported}"
      - "Reason: {reason}"
      - "Server: {server}" # Will ne replaced with the world name if the server is Bukkit/Spigot/Paper
    footer:
      text: "Powered by EverReport - Version 1.0.0"
      icon_url: null

messages:
  on_report: "&aYour report has been sent to the staff."
  cant_report: "&cYou can't report staff members." # Permission to bypass reports: everreport.bypass
  error_console: "&cYou cannot execute this command in the console."
  error_not_online: "&cThis player is not online."
  error_report_self: "&cYou can't report yourself."
  usage: "&cUsage: /report <player> <reason>"
  report_recieved: # Displayed to players with permissions: everreport.alerts
    - "A new report has been received."
    - "Executor: {executor}"
    - "Reported: {reported}"
    - "Reason: {reason}"
